import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const poppins = Poppins({ subsets: ["latin"] ,weight:["400"]});

export const metadata = {
  title: "USB Activation Portal by Tata Motors",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="max-width">
      <body className={poppins.className}><Nav></Nav>{children}</body>
    </html>
  );
}
